apiVersion: apps/v1
kind: Deployment
metadata:
  name: camel-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-microservice
  template:
    metadata:
      labels:
        app: camel-microservice
    spec:
      containers:
        - name: camel-microservice
          image: sachetwasti61/camel-microservice
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "512Mi"
          ports:
            - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: camel-microservice-srv
spec:
  selector:
    app: camel-microservice
  ports:
    - port: 8181
      targetPort: 8181